package com.nebulahelix.torre3.entity;
// Generated 17/03/2015 02:07:05 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Anuncios generated by hbm2java
 */
public class Anuncios  implements java.io.Serializable {


     private Integer idAnuncio;
     private Usuarios usuarios;
     private String titulo;
     private Date fechaPublicacion;
     private Date fechaExpiracion;
     private String contenido;
     private int seccion;
     private int piso;
     private int bloque;

    public Anuncios() {
    }

    public Anuncios(Usuarios usuarios, String titulo, Date fechaPublicacion, Date fechaExpiracion, String contenido, int seccion, int piso, int bloque) {
       this.usuarios = usuarios;
       this.titulo = titulo;
       this.fechaPublicacion = fechaPublicacion;
       this.fechaExpiracion = fechaExpiracion;
       this.contenido = contenido;
       this.seccion = seccion;
       this.piso = piso;
       this.bloque = bloque;
    }
   
    public Integer getIdAnuncio() {
        return this.idAnuncio;
    }
    
    public void setIdAnuncio(Integer idAnuncio) {
        this.idAnuncio = idAnuncio;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Date getFechaPublicacion() {
        return this.fechaPublicacion;
    }
    
    public void setFechaPublicacion(Date fechaPublicacion) {
        this.fechaPublicacion = fechaPublicacion;
    }
    public Date getFechaExpiracion() {
        return this.fechaExpiracion;
    }
    
    public void setFechaExpiracion(Date fechaExpiracion) {
        this.fechaExpiracion = fechaExpiracion;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public int getSeccion() {
        return this.seccion;
    }
    
    public void setSeccion(int seccion) {
        this.seccion = seccion;
    }
    public int getPiso() {
        return this.piso;
    }
    
    public void setPiso(int piso) {
        this.piso = piso;
    }
    public int getBloque() {
        return this.bloque;
    }
    
    public void setBloque(int bloque) {
        this.bloque = bloque;
    }




}


