package com.nebulahelix.torre3.entity;
// Generated 17/03/2015 02:07:05 PM by Hibernate Tools 4.3.1



/**
 * Avatar generated by hbm2java
 */
public class Avatar  implements java.io.Serializable {


     private Integer idAvatar;
     private Usuarios usuarios;
     private int cabeza;
     private int torso;
     private int brazos;
     private int piernas;

    public Avatar() {
    }

    public Avatar(Usuarios usuarios, int cabeza, int torso, int brazos, int piernas) {
       this.usuarios = usuarios;
       this.cabeza = cabeza;
       this.torso = torso;
       this.brazos = brazos;
       this.piernas = piernas;
    }
   
    public Integer getIdAvatar() {
        return this.idAvatar;
    }
    
    public void setIdAvatar(Integer idAvatar) {
        this.idAvatar = idAvatar;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public int getCabeza() {
        return this.cabeza;
    }
    
    public void setCabeza(int cabeza) {
        this.cabeza = cabeza;
    }
    public int getTorso() {
        return this.torso;
    }
    
    public void setTorso(int torso) {
        this.torso = torso;
    }
    public int getBrazos() {
        return this.brazos;
    }
    
    public void setBrazos(int brazos) {
        this.brazos = brazos;
    }
    public int getPiernas() {
        return this.piernas;
    }
    
    public void setPiernas(int piernas) {
        this.piernas = piernas;
    }




}


