package com.nebulahelix.torre3.entity;
// Generated 17/03/2015 02:07:05 PM by Hibernate Tools 4.3.1



/**
 * Proyectos generated by hbm2java
 */
public class Proyectos  implements java.io.Serializable {


     private Integer idProyecto;
     private Usuarios usuarios;
     private String nombre;
     private String descripcion;
     private boolean activo;

    public Proyectos() {
    }

    public Proyectos(Usuarios usuarios, String nombre, String descripcion, boolean activo) {
       this.usuarios = usuarios;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.activo = activo;
    }
   
    public Integer getIdProyecto() {
        return this.idProyecto;
    }
    
    public void setIdProyecto(Integer idProyecto) {
        this.idProyecto = idProyecto;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }




}


