package com.nebulahelix.torre3.entity;
// Generated 17/03/2015 02:07:05 PM by Hibernate Tools 4.3.1



/**
 * Skills generated by hbm2java
 */
public class Skills  implements java.io.Serializable {


     private Integer idSkill;
     private Usuarios usuarios;
     private String skill;
     private int tipoSkill;

    public Skills() {
    }

    public Skills(Usuarios usuarios, String skill, int tipoSkill) {
       this.usuarios = usuarios;
       this.skill = skill;
       this.tipoSkill = tipoSkill;
    }
   
    public Integer getIdSkill() {
        return this.idSkill;
    }
    
    public void setIdSkill(Integer idSkill) {
        this.idSkill = idSkill;
    }
    public Usuarios getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Usuarios usuarios) {
        this.usuarios = usuarios;
    }
    public String getSkill() {
        return this.skill;
    }
    
    public void setSkill(String skill) {
        this.skill = skill;
    }
    public int getTipoSkill() {
        return this.tipoSkill;
    }
    
    public void setTipoSkill(int tipoSkill) {
        this.tipoSkill = tipoSkill;
    }




}


